=== a5216652166/xmdns/res/db/TEMPLATES/host_list.dtd
<!ELEMENT host_list (host*)>
<!ELEMENT host (hostname,shortname,domainname,action*,createdBy?,dateCreated?,description*,known-duplicate?,macAddress*,manager?,modifiedBy?,modifiedDate?,notes*,(a|aaaa|cname|loc|mx|ns|ptr|rp|srv|txt)+)>
<!ELEMENT hostname (#PCDATA)>
<!ELEMENT shortname (#PCDATA)>
<!ELEMENT domainname (#PCDATA)>
<!ELEMENT action (#PCDATA)>
<!ELEMENT createdBy (#PCDATA)>
<!ELEMENT createdDate (#PCDATA)>
<!ELEMENT description (#PCDATA)>
<!ELEMENT known-duplicate (#PCDATA)>
<!ELEMENT macAddress (#PCDATA)>
<!ELEMENT manager (#PCDATA)>
<!ELEMENT modifiedBy (#PCDATA)>
<!ELEMENT modifiedDate (#PCDATA)>
<!ELEMENT notes (#PCDATA)>
<!-- records -->
<!ELEMENT a (#PCDATA)>
<!ELEMENT aaaa (#PCDATA)>
<!ELEMENT cname (#PCDATA)>
<!ELEMENT loc (#PCDATA)>
<!ELEMENT mx (#PCDATA)>
<!ELEMENT ns (#PCDATA)>
<!ELEMENT ptr (#PCDATA)>
<!ELEMENT rp (#PCDATA)>
<!ELEMENT srv (#PCDATA)>
<!ELEMENT txt (#PCDATA)>
<!-- record attributes -->
<!ATTLIST a	net	(PIPE_SEPARATED_NET_LIST) #REQUIRED>
<!ATTLIST aaaa	net	(PIPE_SEPARATED_NET_LIST) #REQUIRED>
<!ATTLIST cname	net	(PIPE_SEPARATED_NET_LIST) #REQUIRED>
<!ATTLIST loc	net	(PIPE_SEPARATED_NET_LIST) #REQUIRED>
<!ATTLIST mx	net	(PIPE_SEPARATED_NET_LIST) #REQUIRED>
<!ATTLIST ns	net	(PIPE_SEPARATED_NET_LIST) #REQUIRED>
<!ATTLIST ptr	net	(PIPE_SEPARATED_NET_LIST) #REQUIRED>
<!ATTLIST rp	net	(PIPE_SEPARATED_NET_LIST) #REQUIRED>
<!ATTLIST srv	net	(PIPE_SEPARATED_NET_LIST) #REQUIRED>
<!ATTLIST txt	net	(PIPE_SEPARATED_NET_LIST) #REQUIRED>
<!-- all DNS records can have a TTL -->
<!ATTLIST a	ttl	CDATA #IMPLIED>
<!ATTLIST aaaa	ttl	CDATA #IMPLIED>
<!ATTLIST cname	ttl	CDATA #IMPLIED>
<!ATTLIST loc	ttl	CDATA #IMPLIED>
<!ATTLIST mx	ttl	CDATA #IMPLIED>
<!ATTLIST ns	ttl	CDATA #IMPLIED>
<!ATTLIST ptr	ttl	CDATA #IMPLIED>
<!ATTLIST rp	ttl	CDATA #IMPLIED>
<!ATTLIST srv	ttl	CDATA #IMPLIED>
<!ATTLIST txt	ttl	CDATA #IMPLIED>

=== a5216652166/xmdns/res/db/host_list.xml
<?xml version="1.0" standalone="yes"?>
<!DOCTYPE host_list SYSTEM "host_list.dtd">
<host_list>
  <host>
    <hostname>example.com</hostname>
    <shortname>example</shortname>
    <domainname>com</domainname>
    <description>Example Domain</description>
    <mx net="example-external">10 mx.example.com.</mx>
    <mx net="example-external">20 mx2.example.com.</mx>
  </host>
  <host>
    <hostname>example.com</hostname>
    <shortname>example</shortname>
    <domainname>com</domainname>
    <description>Example Domain</description>
    <known-duplicate>This makes configuration of the domain easier.</known-duplicate>
    <ns net="globalnet">ns1.example.com</ns>
    <ns net="globalnet">ns2.example.com</ns>
  </host>
  <host>
    <hostname>sd.example.com</hostname>
    <shortname>sd</shortname>
    <domainname>example.com</domainname>
    <description>Example Sub-Domain</description>
    <ns net="example-internal">internal-ns1.sd.example.com</ns>
    <ns net="example-internal">internal-ns2.sd.example.com</ns>
    <ns net="globalnet">ns1.sd.example.com</ns>
    <ns net="globalnet">ns2.sd.example.com</ns>
  </host>
  <host>
    <hostname>puppy.sd.example.com</hostname>
    <shortname>puppy</shortname>
    <domainname>sd.example.com</domainname>
    <description>Example kerberos server</description>
    <a net="example-dual-stack">192.0.2.5</a>
    <aaaa net="example-dual-stack">2001:db8::5</aaaa>
  </host>
  <host>
    <hostname>_kerberos._udp.sd.example.com</hostname>
    <shortname>_kerberos._udp</shortname>
    <domainname>sd.example.com</domainname>
    <description>SRV helper records for the kerberos realm SD.EXAMPLE.COM</description>
    <notes>puppy will be used primarily and dog is used in case of failure</notes>
    <srv net="globalnet">0 1 88 puppy.sd.example.com</srv>
    <srv net="globalnet">1 1 88 dog.sd.example.com</srv>
  </host>
</host_list>
