=== a5216652166/xmdns/res/db/net_list.dtd
<!ELEMENT net_list (network*)>
<!ELEMENT network (name,color?,description?,prefix*,notes*,default-mx*,match-clients*,ignore-ipv4-reverse-resolve?,no-global-reverse-resolve?,ns*,extra-reverse*,(resolve+|no-resolve))>
<!ELEMENT name (#PCDATA)>
<!ELEMENT color (#PCDATA)>
<!ELEMENT description (#PCDATA)>
<!ELEMENT default-mx (#PCDATA)>
<!-- Extra networks to reverse resolve within this view -->
<!ELEMENT extra-reverse (#PCDATA)> 
<!ELEMENT notes (#PCDATA)>
<!-- entries to put in the named.acls file that gets fed to match-clients in named.views
     Each entry should be a ip or ip range:
     192.168.0.1
     192.168.0.0/24
     2607:f088:0:1::1
     2607:f088:0:1::/64 -->
<!ELEMENT match-clients (#PCDATA)>
<!-- Do not reverse-resolve this network globally, add extra-reverse to resolve for specific views -->
<!ELEMENT no-global-reverse-resolve EMPTY>
<!ELEMENT ignore-ipv4-reverse-resolve EMPTY>
<!-- Authoritative Name Server for network -->
<!ELEMENT ns (#PCDATA)>
<!-- For networks that are covered by another view (virtual/aggregate network) -->
<!ELEMENT no-resolve EMPTY>
<!-- an ordered list of these specifies the preferential network in a view
     Each entry should be a physical network name -->
<!ELEMENT resolve (#PCDATA)>
<!--
  records
-->
<!ELEMENT prefix (#PCDATA)>
<!--
  element attributes
-->
<!ATTLIST extra-reverse	proto	(ipv4|ipv6) #REQUIRED>
<!ATTLIST prefix	proto	(ipv4|ipv6) #REQUIRED>
<!ATTLIST network	type	(virtual|aggregate|physical) #REQUIRED>
<!ATTLIST network	recursion	(yes|no) #REQUIRED>
<!ATTLIST network	filter	(none|only-ipv4|only-ipv6) 'none'>
<!ATTLIST match-clients	special	(none|any|localhost|localnets|ip) 'ip'>

=== a5216652166/xmdns/res/db/net_list.xml
<?xml version="1.0" standalone="yes"?>
<!DOCTYPE net_list SYSTEM "net_list.dtd">
<net_list>
  <network recursion="yes" type="virtual">
    <name>admin-hosts</name>
    <description>Administrative hosts that can resolve everything</description>
    <!-- Administrative Clients -->
    <match-clients>192.0.2.10</match-clients>
    <match-clients>192.0.2.11</match-clients>
    <resolve>admin-hosts</resolve>
    <resolve>example-dual-stack</resolve>
    <resolve>example-private</resolve>
    <resolve>example-internal</resolve>
    <resolve>example-external</resolve>
    <resolve>globalnet</resolve>
  </network>
  <network recursion="yes" type="physical">
    <name>example-dual-stack</name>
    <prefix proto="ipv4">192.0.2.0/24</prefix>
    <prefix proto="ipv6">2001:db8::/64</prefix>
    <ns>ns1.example.com</ns>
    <ns>ns1.example.com</ns>
    <resolve>example-dual-stack</resolve>
    <resolve>example-external</resolve>
    <resolve>globalnet</resolve>
  </network>
  <network recursion="yes" type="physical">
    <name>example-private</name>
    <prefix proto="ipv4">192.168.0.1/24</prefix>
    <ns>ns1.example.com</ns>
    <ns>ns1.example.com</ns>
    <resolve>example-private</resolve>
    <resolve>example-dual-stack</resolve>
    <resolve>example-external</resolve>
    <resolve>globalnet</resolve>
  </network>
  <network recursion="yes" type="physical">
    <name>example-internal</name>
    <description>An internal network, possibly firewalled off</description>
    <prefix proto="ipv4">192.0.3.0/24</prefix>
    <ns>ns1.example.com</ns>
    <ns>ns2.example.com</ns>
    <resolve>example-internal</resolve>
    <resolve>example-dual-stack</resolve>
    <resolve>example-external</resolve>
    <resolve>globalnet</resolve>
  </network>
  <network recursion="yes" type="physical">
    <name>example-external</name>
    <description>An external network, possibly firewalled off</description>
    <prefix proto="ipv4">192.0.4.0/24</prefix>
    <ns>ns1.example.com</ns>
    <ns>ns2.example.com</ns>
    <resolve>example-external</resolve>
    <resolve>example-dual-stack</resolve>
    <resolve>globalnet</resolve>
  </network>
  <network recursion="no" type="physical">
    <name>example-stub</name>
    <description>A non-resolving network</description>
    <prefix proto="ipv4">192.168.1.0/24</prefix>
    <ns>ns1.tajinc.org</ns>
    <ns>ns2.tajinc.org</ns>
    <no-resolve/>
  </network>
  <network recursion="no" type="virtual">
    <name>globalnet</name>
    <description>Define Global (catchall) Resolve Priority</description>
    <match-clients special="any" />
    <resolve>globalnet</resolve>
    <resolve>example-dual-stack</resolve>
    <resolve>example-external</resolve>
  </network>
</net_list>
